### ISSUE TITLE
Does not work with 4.11.2 Launcher Version

### ISSUE THREAD

**Issue by HeadClot** [vagenv/BlockConstructor#2]
Here are the errors that I get with Version from Binary 4.11.2 Version from Launcher. 

http://i.imgur.com/OYdbt1c.png

http://i.imgur.com/M7yvOwe.png

Will attach my log file soon.

**Comment by HeadClot** [comment]
Ok,

I am attaching my log file - As it still does not run. I am still getting the above errors.

> 
> Log file open, 04/28/16 15:07:22
> LogInit:Display: Running engine for game: BlockFPS
> LogPlatformFile: Not using cached read wrapper
> LogInit:Display: RandInit(1401014462) SRandInit(1401014464).
> LogTaskGraph: Started task graph with 4 named threads and 6 total threads.
> LogStats: Stats thread started at 0.078265
> LogModuleManager:Warning: Found module file ../../../../../../Users/Ben/Documents/Unreal Projects/BlockFPS/Plugins/BlockConstructorPlugin/Binaries/Win64/UE4Editor-BlockConstructorPlugin.dll (API version 0), but it was incompatible with the current engine API version (2927265). This is likely a stale module that must be recompiled.
> LogInit: Version: 4.11.2-2946394+++UE4+Release-4.11
> LogInit: API Version: 2927265
> LogInit: Compiled (64-bit): Apr 18 2016 02:18:46
> LogInit: Compiled with Visual C++: 19.00.23026.00
> LogInit: Build Configuration: Development
> LogInit: Branch Name: ++UE4+Release-4.11
> LogInit: Command line:  
> LogInit: Base directory: C:/Program Files (x86)/Epic Games/4.11/Engine/Binaries/Win64/
> LogInit: Installed Engine Build: 1
> LogInit: Using libcurl 7.41.0
> LogInit:  - built for x86_64-pc-win32
> LogInit:  - supports SSL with WinSSL
> LogInit:  - other features:
> LogInit:      CURL_VERSION_SSL
> LogInit:      CURL_VERSION_IPV6
> LogInit:      CURL_VERSION_ASYNCHDNS
> LogInit:      CURL_VERSION_LARGEFILE
> LogInit:      CURL_VERSION_IDN
> LogInit:  CurlRequestOptions (configurable via config and command line):
> LogInit:  - bVerifyPeer = true  - Libcurl will verify peer certificate
> LogInit:  - bUseHttpProxy = false  - Libcurl will NOT use HTTP proxy
> LogInit:  - bDontReuseConnections = false  - Libcurl will reuse connections
> LogInit:  - CertBundlePath = nullptr  - Libcurl will use whatever was configured at build time.
> LogInit: Presizing for max 16777216 objects, including 0 objects not considered by GC, pre-allocating 0 bytes for permanent pool.
> LogInit: Object subsystem initialized
> [2016.04.28-21.07.26:292][  0]LogInit: Selected Device Profile: [Windows]
> [2016.04.28-21.07.26:292][  0]LogInit: Applying CVar settings loaded from the selected device profile: [Windows]
> [2016.04.28-21.07.26:306][  0]LogInit: Computer: BEN-PC
> [2016.04.28-21.07.26:306][  0]LogInit: User: Ben
> [2016.04.28-21.07.26:306][  0]LogInit: CPU Page size=65536, Cores=3
> [2016.04.28-21.07.26:306][  0]LogInit: High frequency timer resolution =3.222704 MHz
> [2016.04.28-21.07.26:306][  0]LogMemory: Memory total: Physical=16.0GB (16GB approx)
> [2016.04.28-21.07.26:306][  0]LogMemory: Platform Memory Stats for Windows
> [2016.04.28-21.07.26:306][  0]LogMemory: Process Physical Memory: 315.08 MB used, 315.08 MB peak
> [2016.04.28-21.07.26:306][  0]LogMemory: Process Virtual Memory: 315.93 MB used, 315.93 MB peak
> [2016.04.28-21.07.26:306][  0]LogMemory: Physical Memory: 5165.25 MB used, 16333.50 MB total
> [2016.04.28-21.07.26:306][  0]LogMemory: Virtual Memory: 684.16 MB used, 134217728.00 MB total
> [2016.04.28-21.07.26:344][  0]LogTextLocalizationManager: No specific translations for ('en-US') exist, so ('en') translations will be used.
> [2016.04.28-21.07.26:878][  0]LogD3D11RHI: D3D11 adapters:
> [2016.04.28-21.07.26:893][  0]LogD3D11RHI:    0. 'AMD Radeon R7 200 Series' (Feature Level 11_0)
> [2016.04.28-21.07.26:893][  0]LogD3D11RHI:       2030MB of dedicated video memory, 0MB of dedicated system memory, and 8166MB of shared system memory, 2 output[s]
> [2016.04.28-21.07.26:895][  0]LogD3D11RHI:    1. 'Microsoft Basic Render Driver' (Feature Level 11_0)
> [2016.04.28-21.07.26:895][  0]LogD3D11RHI:       0MB of dedicated video memory, 0MB of dedicated system memory, and 8166MB of shared system memory, 0 output[s]
> [2016.04.28-21.07.26:895][  0]LogD3D11RHI: Chosen D3D11 Adapter: 0
> [2016.04.28-21.07.26:902][  0]LogD3D11RHI: Creating new Direct3DDevice
> [2016.04.28-21.07.26:902][  0]LogD3D11RHI:     Adapter Name: AMD Radeon R7 200 Series
> [2016.04.28-21.07.26:902][  0]LogD3D11RHI:   Driver Version: Catalyst 15.8 (internal 16.150.2211.0)
> [2016.04.28-21.07.26:902][  0]LogD3D11RHI:      Driver Date: 3-21-2016
> [2016.04.28-21.07.26:902][  0]LogRHI: Texture pool is 1361 MB (70% of 1945 MB)
> [2016.04.28-21.07.26:911][  0]LogD3D11RHI: Async texture creation disabled: no driver support
> [2016.04.28-21.07.26:924][  0]LogShaderCompilers: Guid format shader working directory is -19 characters bigger than the processId version (../../../../../../Users/Ben/Documents/Unreal Projects/BlockFPS/Intermediate/Shaders/WorkingDirectory/11900/).
> [2016.04.28-21.07.26:925][  0]LogShaderCompilers: Cleaned the shader compiler working directory 'C:/Users/Ben/AppData/Local/Temp/UnrealShaderWorkingDir/7486FB294740079D068360A011D028EF/'.
> [2016.04.28-21.07.26:925][  0]LogShaderCompilers:Display: Using Local Shader Compiler.
> [2016.04.28-21.07.28:248][  0]LogTemp:Display: Loaded TP AllDesktopTargetPlatform
> [2016.04.28-21.07.28:256][  0]LogTemp:Display: Loaded TP WindowsClientTargetPlatform
> [2016.04.28-21.07.28:262][  0]LogTemp:Display: Loaded TP WindowsNoEditorTargetPlatform
> [2016.04.28-21.07.28:269][  0]LogTemp:Display: Loaded TP WindowsServerTargetPlatform
> [2016.04.28-21.07.28:276][  0]LogTemp:Display: Loaded TP WindowsTargetPlatform
> [2016.04.28-21.07.28:282][  0]LogTemp:Display: Loaded TP AndroidTargetPlatform
> [2016.04.28-21.07.28:286][  0]LogTemp:Display: Loaded TP Android_ASTCTargetPlatform
> [2016.04.28-21.07.28:291][  0]LogTemp:Display: Loaded TP Android_ATCTargetPlatform
> [2016.04.28-21.07.28:296][  0]LogTemp:Display: Loaded TP Android_DXTTargetPlatform
> [2016.04.28-21.07.28:300][  0]LogTemp:Display: Loaded TP Android_ETC1TargetPlatform
> [2016.04.28-21.07.28:306][  0]LogTemp:Display: Loaded TP Android_ETC2TargetPlatform
> [2016.04.28-21.07.28:315][  0]LogTemp:Display: Loaded TP Android_MultiTargetPlatform
> [2016.04.28-21.07.28:315][  0]LogTemp:Display: Loaded TP Android_PVRTCTargetPlatform
> [2016.04.28-21.07.28:316][  0]LogTemp:Display: Loaded TP HTML5TargetPlatform
> [2016.04.28-21.07.28:337][  0]LogTemp:Display: Loaded TP IOSTargetPlatform
> [2016.04.28-21.07.28:341][  0]LogTemp:Display: Loaded TP TVOSTargetPlatform
> [2016.04.28-21.07.28:346][  0]LogTemp:Display: Loaded TP LinuxNoEditorTargetPlatform
> [2016.04.28-21.07.28:350][  0]LogTemp:Display: Loaded TP LinuxServerTargetPlatform
> [2016.04.28-21.07.28:355][  0]LogTemp:Display: Loaded TP LinuxTargetPlatform
> [2016.04.28-21.07.28:355][  0]LogTargetPlatformManager:Display: Building Assets For Windows
> [2016.04.28-21.07.28:475][  0]LogDerivedDataCache:Display: Max Cache Size: 512 MB
> [2016.04.28-21.07.28:558][  0]LogDerivedDataCache: Loaded boot cache 0.08s 46MB C:/Users/Ben/AppData/Local/UnrealEngine/4.11/DerivedDataCache/Boot.ddc.
> [2016.04.28-21.07.28:558][  0]LogDerivedDataCache:Display: Loaded Boot cache: C:/Users/Ben/AppData/Local/UnrealEngine/4.11/DerivedDataCache/Boot.ddc
> [2016.04.28-21.07.28:558][  0]LogDerivedDataCache: FDerivedDataBackendGraph:  Pak pak cache file ../../../../../../Users/Ben/Documents/Unreal Projects/BlockFPS/DerivedDataCache/DDC.ddp not found, will not use a pak cache.
> [2016.04.28-21.07.28:558][  0]LogDerivedDataCache: Unable to find inner node Pak for hierarchical cache Hierarchy.
> [2016.04.28-21.07.28:558][  0]LogDerivedDataCache: FDerivedDataBackendGraph:  CompressedPak pak cache file ../../../../../../Users/Ben/Documents/Unreal Projects/BlockFPS/DerivedDataCache/Compressed.ddp not found, will not use a pak cache.
> [2016.04.28-21.07.28:558][  0]LogDerivedDataCache: Unable to find inner node CompressedPak for hierarchical cache Hierarchy.
> [2016.04.28-21.07.28:578][  0]LogDerivedDataCache:Display: Pak cache opened for reading ../../../Engine/DerivedDataCache/Compressed.ddp.
> [2016.04.28-21.07.28:591][  0]LogDerivedDataCache: Using Local data cache path C:/Users/Ben/AppData/Local/UnrealEngine/Common/DerivedDataCache: Writable
> [2016.04.28-21.07.28:652][  0]LogModuleManager:Warning: Found module file ../../../../../../Users/Ben/Documents/Unreal Projects/BlockFPS/Plugins/BlockConstructorPlugin/Binaries/Win64/UE4Editor-UObjectPlugin.dll (API version 0), but it was incompatible with the current engine API version (2927265). This is likely a stale module that must be recompiled.
> [2016.04.28-21.07.28:655][  0]LogModuleManager:Warning: Found module file ../../../../../../Users/Ben/Documents/Unreal Projects/BlockFPS/Plugins/BlockConstructorPlugin/Binaries/Win64/UE4Editor-BlockConstructorPlugin.dll (API version 0), but it was incompatible with the current engine API version (2927265). This is likely a stale module that must be recompiled.
> [2016.04.28-21.07.28:844][  0]LogInit: Selected Device Profile: [Windows]
> [2016.04.28-21.07.28:845][  0]LogContentStreaming: Texture pool size is 0.00 MB
> [2016.04.28-21.07.28:895][  0]LogMaterial: Uniform references updated for custom material expression Custom.
> [2016.04.28-21.07.29:069][  0]LogMeshUtilities: No automatic mesh reduction module available
> [2016.04.28-21.07.29:069][  0]LogMeshUtilities: No automatic mesh merging module available
> [2016.04.28-21.07.29:069][  0]LogMeshUtilities: No distributed automatic mesh merging module available
> [2016.04.28-21.07.29:460][  0]LogUObjectArray: 27679 objects as part of root set at end of initial load.
> [2016.04.28-21.07.29:460][  0]LogUObjectAllocator: 5591592 out of 0 bytes used by permanent object pool.
> [2016.04.28-21.07.29:460][  0]LogUObjectArray: CloseDisregardForGC: 0/0 objects in disregard for GC pool
> [2016.04.28-21.07.29:470][  0]LogInit: WinSock: version 1.1 (2.2), MaxSocks=32767, MaxUdp=65467
> [2016.04.28-21.07.29:598][  0]LogSlate: SlateFontCache - WITH_FREETYPE: 1, WITH_HARFBUZZ: 1
> [2016.04.28-21.07.29:598][  0]LogSlate: SlateFontCache - WITH_FREETYPE: 1, WITH_HARFBUZZ: 1
> [2016.04.28-21.07.29:729][  0]LogStreaming:Warning: Failed to read file '../../../Engine/Content/Editor/Slate/Common/Selection_16x.png' error.
> [2016.04.28-21.07.29:729][  0]LogSlate: Could not find file for Slate resource: ../../../Engine/Content/Editor/Slate/Common/Selection_16x.png
> [2016.04.28-21.07.29:730][  0]LogStreaming:Warning: Failed to read file '../../../Engine/Content/Editor/Slate/Common/Selection_16x.png' error.
> [2016.04.28-21.07.29:730][  0]LogSlate: Could not find file for Slate resource: ../../../Engine/Content/Editor/Slate/Common/Selection_16x.png
> [2016.04.28-21.07.29:730][  0]LogStreaming:Warning: Failed to read file '../../../Engine/Content/Editor/Slate/Common/Selection_16x.png' error.
> [2016.04.28-21.07.29:730][  0]LogSlate: Could not find file for Slate resource: ../../../Engine/Content/Editor/Slate/Common/Selection_16x.png
> [2016.04.28-21.07.30:454][  0]LogUdpMessaging: Initializing bridge on interface 0.0.0.0:0 to multicast group 230.0.0.1:6666.
> [2016.04.28-21.07.30:571][  0]LogAssetRegistry: FAssetRegistry took 0.0224 seconds to start up
> [2016.04.28-21.07.30:806][  0]SourceControl: Info Source control is disabled
> [2016.04.28-21.07.30:855][  0]SourceControl: Info Source control is disabled
> [2016.04.28-21.07.30:869][  0]SourceControl: Info Source control is disabled
> [2016.04.28-21.07.30:883][  0]SourceControl: Info Source control is disabled
> [2016.04.28-21.07.30:895][  0]LogModuleManager:Warning: Found module file C:/Users/Ben/Documents/Unreal Projects/BlockFPS/Plugins/BlockConstructorPlugin/Binaries/Win64/UE4Editor-UObjectPlugin.dll (API version 0), but it was incompatible with the current engine API version (2927265). This is likely a stale module that must be recompiled.
> [2016.04.28-21.07.39:749][  0]LogWindowsTextInputMethodSystem:Display: IME system now deactivated.
> [2016.04.28-21.07.39:749][  0]LogWindowsTextInputMethodSystem:Display: IME system now deactivated.
> [2016.04.28-21.07.39:807][  0]LogExit: Preparing to exit.
> [2016.04.28-21.07.40:707][  0]LogObj: Freed 0b from 0 cluster array pools.
> [2016.04.28-21.07.40:707][  0]LogExit: Object subsystem successfully closed.
> [2016.04.28-21.07.40:716][  0]LogD3D11RHI: Shutdown
> [2016.04.28-21.07.40:716][  0]LogD3D11RHI: CleanupD3DDevice
> [2016.04.28-21.07.40:735][  0]LogD3D11RHI: ~FD3D11DynamicRHI
> [2016.04.28-21.07.41:093][  0]LogDerivedDataCache: Shutdown
> [2016.04.28-21.07.41:093][  0]LogModuleManager: Shutting down and abandoning module SubversionSourceControl (107)
> [2016.04.28-21.07.41:093][  0]LogModuleManager: Shutting down and abandoning module PerforceSourceControl (106)
> [2016.04.28-21.07.41:093][  0]LogModuleManager: Shutting down and abandoning module SourceControl (105)
> [2016.04.28-21.07.41:093][  0]LogModuleManager: Shutting down and abandoning module GitSourceControl (104)
> [2016.04.28-21.07.41:093][  0]LogModuleManager: Shutting down and abandoning module LightPropagationVolumeEditor (103)
> [2016.04.28-21.07.41:093][  0]LogModuleManager: Shutting down and abandoning module PaperTiledImporter (102)
> [2016.04.28-21.07.41:093][  0]LogModuleManager: Shutting down and abandoning module PaperSpriteSheetImporter (101)
> [2016.04.28-21.07.41:093][  0]LogModuleManager: Shutting down and abandoning module MeshPaint (100)
> [2016.04.28-21.07.41:093][  0]LogModuleManager: Shutting down and abandoning module HotReload (99)
> [2016.04.28-21.07.41:094][  0]LogModuleManager: Shutting down and abandoning module MainFrame (98)
> [2016.04.28-21.07.41:094][  0]LogModuleManager: Shutting down and abandoning module LevelEditor (97)
> [2016.04.28-21.07.41:095][  0]LogModuleManager: Shutting down and abandoning module DirectoryWatcher (96)
> [2016.04.28-21.07.41:096][  0]LogModuleManager: Shutting down and abandoning module AssetRegistry (95)
> [2016.04.28-21.07.41:210][  0]LogModuleManager: Shutting down and abandoning module ContentBrowser (94)
> [2016.04.28-21.07.41:210][  0]LogModuleManager: Shutting down and abandoning module Paper2DEditor (93)
> [2016.04.28-21.07.41:210][  0]LogModuleManager: Shutting down and abandoning module UdpMessaging (92)
> [2016.04.28-21.07.41:311][  0]LogModuleManager: Shutting down and abandoning module LightPropagationVolumeRuntime (91)
> [2016.04.28-21.07.41:311][  0]LogModuleManager: Shutting down and abandoning module Paper2D (90)
> [2016.04.28-21.07.41:311][  0]LogModuleManager: Shutting down and abandoning module WindowsMoviePlayer (89)
> [2016.04.28-21.07.41:311][  0]LogModuleManager: Shutting down and abandoning module Media (88)
> [2016.04.28-21.07.41:311][  0]LogModuleManager: Shutting down and abandoning module WmfMedia (87)
> [2016.04.28-21.07.41:311][  0]LogModuleManager: Shutting down and abandoning module MediaAssets (86)
> [2016.04.28-21.07.41:311][  0]LogModuleManager: Shutting down and abandoning module GameLiveStreaming (85)
> [2016.04.28-21.07.41:311][  0]LogModuleManager: Shutting down and abandoning module GameplayTagsEditor (84)
> [2016.04.28-21.07.41:311][  0]LogModuleManager: Shutting down and abandoning module OnlineBlueprintSupport (83)
> [2016.04.28-21.07.41:311][  0]LogModuleManager: Shutting down and abandoning module GameplayTasksEditor (82)
> [2016.04.28-21.07.41:311][  0]LogModuleManager: Shutting down and abandoning module PropertyEditor (81)
> [2016.04.28-21.07.41:312][  0]LogModuleManager: Shutting down and abandoning module BehaviorTreeEditor (80)
> [2016.04.28-21.07.41:312][  0]LogModuleManager: Shutting down and abandoning module FunctionalTesting (79)
> [2016.04.28-21.07.41:312][  0]LogModuleManager: Shutting down and abandoning module CollisionAnalyzer (78)
> [2016.04.28-21.07.41:312][  0]LogModuleManager: Shutting down and abandoning module WorkspaceMenuStructure (77)
> [2016.04.28-21.07.41:312][  0]LogModuleManager: Shutting down and abandoning module MessageLog (76)
> [2016.04.28-21.07.41:312][  0]LogModuleManager: Shutting down and abandoning module Sequencer (75)
> [2016.04.28-21.07.41:312][  0]LogModuleManager: Shutting down and abandoning module AssetTools (74)
> [2016.04.28-21.07.41:312][  0]LogModuleManager: Shutting down and abandoning module UMGEditor (73)
> [2016.04.28-21.07.41:312][  0]LogModuleManager: Shutting down and abandoning module UMG (72)
> [2016.04.28-21.07.41:312][  0]LogModuleManager: Shutting down and abandoning module SlateReflector (71)
> [2016.04.28-21.07.41:312][  0]LogModuleManager: Shutting down and abandoning module Slate (70)
> [2016.04.28-21.07.41:312][  0]LogModuleManager: Shutting down and abandoning module EditorStyle (69)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module SessionServices (68)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module SourceCodeAccess (67)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module HeadMountedDisplay (66)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module XAudio2 (65)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module Networking (63)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module Core (62)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module KismetCompiler (61)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module PhysXFormats (60)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module MeshUtilities (59)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module CookingStats (58)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module DerivedDataCache (57)
> [2016.04.28-21.07.41:320][  0]LogDerivedDataCache: Shutdown
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module ShaderFormatOpenGL (56)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module ShaderFormatD3D (55)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module MetalShaderFormat (54)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module TextureFormatUncompressed (53)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module TextureFormatPVR (52)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module TextureFormatIntelISPCTexComp (51)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module TextureFormatDXT (50)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module ImageWrapper (49)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module TextureFormatASTC (48)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module TextureFormatAndroid (47)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module AudioFormatOpus (46)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module AudioFormatOgg (45)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module AudioFormatADPCM (44)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module LinuxTargetPlatform (43)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module LinuxServerTargetPlatform (42)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module LinuxNoEditorTargetPlatform (41)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module TVOSTargetPlatform (40)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module Messaging (39)
> [2016.04.28-21.07.41:320][  0]LogModuleManager: Shutting down and abandoning module IOSTargetPlatform (38)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module HTML5TargetPlatform (37)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module Android_PVRTCTargetPlatform (36)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module Android_MultiTargetPlatform (35)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module Android_ETC2TargetPlatform (34)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module Android_ETC1TargetPlatform (33)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module Android_DXTTargetPlatform (32)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module Android_ATCTargetPlatform (31)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module Android_ASTCTargetPlatform (30)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module AndroidTargetPlatform (29)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module WindowsTargetPlatform (28)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module WindowsServerTargetPlatform (27)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module WindowsNoEditorTargetPlatform (26)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module WindowsClientTargetPlatform (25)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module AllDesktopTargetPlatform (24)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module TargetPlatform (23)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module InputCore (22)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module Settings (21)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module OnlineSubsystem (19)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module HTTP (18)
> [2016.04.28-21.07.41:321][  0]LogModuleManager: Shutting down and abandoning module XMPP (17)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module OculusRift (16)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module ExampleDeviceProfileSelector (15)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module TextureCompressor (14)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module ShaderCore (13)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module Landscape (12)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (11)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module OpenGLDrv (10)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module D3D11RHI (9)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (8)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module Renderer (7)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module Engine (6)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module CoreUObject (5)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module NetworkFile (4)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module StreamingFile (3)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module SandboxFile (2)
> [2016.04.28-21.07.41:322][  0]LogModuleManager: Shutting down and abandoning module PakFile (1)
> [2016.04.28-21.07.41:327][  0]LogExit: Exiting.
> [2016.04.28-21.07.41:331][  0]Log file closed, 04/28/16 15:07:41
>

**Comment by vagenv** [comment]
> [2016.04.28-21.07.30:895][ 0]LogModuleManager:Warning: Found module file C:/Users/Ben/Documents/Unreal Projects/BlockFPS/Plugins/BlockConstructorPlugin/Binaries/Win64/UE4Editor-UObjectPlugin.dll (API version 0), but it was incompatible with the current engine API version (2927265). This is likely a stale module that must be recompiled.

Searching around I think I found the a solution.

I deleted Intermediate folder and rebuild the project again.

Please check again if still doesn't work I will rebuild the whole engine and plugin as one.

**Comment by HeadClot** [comment]
Hey @vagenv - Sounds like a plan. Will let you know if it works or not. When you upload it ofc. :)

**Comment by vagenv** [comment]
Um I already updated it.

I am going to sleep and in the morning I will check it.

**Comment by HeadClot** [comment]
Alright I got it working!

Here is what I did -

1. Made a C++ project that got rid of this error. [Link](http://i.imgur.com/OYdbt1c.png)
2. I went to Unreal Projects\Block_FPS\Plugins\BlockConstructorPlugin\Binaries\Win64
and Deleted every file and did a build for the project with VS 2015 with Update 2.
3. The file UE4Editor-UObjectPlugin.dll seemed to be compiled for Unreal Engine Version 4.10.1 So I deleted that.
4. Start the Editor and the editor works.

Going to do some further testing and I will get back to you. :)

**Comment by vagenv** [comment]
Engine and Plugin recompiled together.

If this still won't work, I don't know what else to do.

Good Luck.

**Comment by DefinitlyEvil** [comment]
Confirmed! @HeadClot 's idea works. ;P

**Comment by AngelTsTsvetkov** [comment]
I made C++ blank project; delete all files in "f:\UnrealEngine Projects\temp2\Plugins\BlockConstructorPlugin\Binaries\Win64\";
 When start compiling in VS2013 Update3=>There are the errors:
 a)
 Error 1 error C2661: 'stat::stat' : no overloaded function takes 2 arguments f:\unrealengine projects\temp2\plugins\blockconstructorplugin\source\blockconstructorplugin\System\LevelBlockConstructor.h 306 1 temp2
 b)
 Error 2 error C2661: 'stat::stat' : no overloaded function takes 2 arguments F:\UnrealEngine Projects\temp2\Plugins\BlockConstructorPlugin\Source\BlockConstructorPlugin\System\LevelBlockConstructor.h 306 1 temp2
 c)
 Error 3 error : Failed to produce item: F:\UnrealEngine Projects\temp2\Plugins\BlockConstructorPlugin\Binaries\Win64\UE4Editor-BlockConstructorPlugin.dll f:\UnrealEngine Projects\temp2\Intermediate\ProjectFiles\ERROR temp2
 d)
 Error 4 error MSB3073: The command "F:\UnrealEngine\Engine\Build\BatchFiles\Build.bat temp2Editor Win64 Development "F:\UnrealEngine Projects\temp2\temp2.uproject" -waitmutex" exited with code -1. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.MakeFile.Targets 38 5 temp2

**Comment by AngelTsTsvetkov** [comment]
There is not necessary of VS2015, I compiled successfully with VS2013 and UE4.11.2, and there is no necessary to delete any files.
in "f:\UnrealEngine Projects\temp\Plugins\BlockConstructorPlugin\Source\BlockConstructorPlugin\System\LevelBlockConstructor.h":
1)insert the line "#include <sys/stat.h>" right after "#pragma once" at the top of the file;
2)replace the line "struct stat buffer;" with "struct _stat buffer;"
3)replace the line "return (stat(name, &buffer) == 0);" with "return (_stat(name, &buffer) == 0);"
Start your project, compile and wait to load Editor
But blueprint file "BlockConstructorCharacter" contains many errors and still can't run. At least the plugin is loaded in Editor.
